# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

after_success:
  - Rscript -e 'covr::codecov()'

language: R
cache: packages
sudo: false
warnings_are_errors: true


os:
  - linux
  - osx
r:
  - release
  - devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - cargo
      - libmagick++-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi
